
version: 2

models:
    - name: dim_product
      description: "A starter dbt model"
      columns:
          - name: ProductID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

 
